### ISSUE TITLE
编译成功运行报错

### ISSUE THREAD

**Issue by 2439905184** [wwwAngHua/Application#5]
你的网站是不是关掉了
```
 Process: com.application.developer, PID: 23760
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.application.developer/com.application.developer.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(java.lang.String)' on a null object reference
        at com.application.developer.FileUtils.getSubString(FileUitls.java:404)
        at com.application.developer.MainActivity.onCreate(MainActivity.java:231)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
```
```
  String versions = GetHttps.getHtml("http://app.huayi-w.cn/application/config.txt");
```

**Comment by wwwAngHua** [comment]
是的，原先作为公告以及更新使用的，后面迁移服务器没有迁移该数据
